<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use mysql_xdevapi\Table;

class Orders_products extends Model
{
    use HasFactory;

    protected $table = 'orders_products';
    protected $primaryKey ='id';
    public $incrementing = true;
    public $timestamps = false;

    protected $fillable = [

    ];

    public function index() {
        // return view('allergens');
    }

    // orders_products n .. 1 order
    public function product(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Orders_products::class,'order_id', 'order_id' );
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::deleting(function ($order_product) {
            $order_product->product()->delete();
        });
    }

}
