<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;

    protected $table = 'orders';
    protected $primaryKey = 'order_id';
    public $timestamps = false; // so, we don't need created_at and updated_at columns
   // protected $with = ['orders_products'];

    protected $fillable = [

    ];

    public function index() {

    }

    public function orders_products(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Orders_products::class, 'order_id', 'order_id');
    }

    public function delivery_lists(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Delivery_list::class, 'order_id', 'order_id');
    }


    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::deleting(function ( Order $order) {
            $order->orders_products()->delete();
        });
    }
}
